### ISSUE TITLE
[翻译申请] contributing/documentation/

### ISSUE THREAD

**Issue by shangguokan** [sfcn/symfony-docs-chs#30]
|文件              |内标题|操作|
|-----------------|------|------|
|overview|参与贡献文档|修订|
|format|文档格式|翻译|
|standards|文档标准|翻译|
|translations|翻译|翻译|
|license|Symfony文档协议|翻译|

**Comment by chrisyue** [comment]
:+1:  效率真高

等你把这篇翻译完了，先缓缓，我们有更好的翻译方案

**Comment by shangguokan** [comment]
什么翻译方案，就我们三个人要翻到猴年马月啊。。。

**Comment by chrisyue** [comment]
sphinx 是支持生成po文件做翻译的，而weblate又是一款在线翻译po文件的工具，明天我打算装一个试试看 <http://weblate.org/zh-hans/>

**Comment by chrisyue** [comment]
你翻译完一篇就先提交吧。决定了换不换方案再翻译剩下的

**Comment by shangguokan** [comment]
我觉得如果人多的话，的确托管在翻译平台上较为方便，方便管理，进度可视化，但是目前来讲git已经足够了，你们决定吧。我先把这个issue翻译完，方便后面加入翻译的人查看。

**Comment by chrisyue** [comment]
好嘞，回来看
